config/routes.rb
Rails.application.routes.draw do

  root 'landing_page#index'

  get '/artists/:id', to: 'artists#show'

  get '/artists/:id/tip', to: 'artists#tip'

  get '/locations', to: 'locations#index'

  resources :locations
  resources :artists


end

app/models/artist.rb
class Artist < ActiveRecord::Base

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  def tip
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:artist, :rating, :tip, :review, :description, :genre, :photo_url)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController

  def index

  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @artists = Artist.all
    @locations = Location.all
    @locations = Location.all
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.infowindow("#{location.title} - #{location.description}")
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @artist = Location.find(params[:id])
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Performer location added.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Performer location updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Performer location removed.' }
      format.json { head :no_content }
    end
  end

  def map

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :tip %><br>
    <%= f.text_field :tip %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Rating</th>
      <th>Tip</th>
      <th>Review</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.artist %></td>
        <td><%= artist.rating %></td>
        <td><%= artist.tip %></td>
        <td><%= artist.review %></td>
        <td><%= artist.genre %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/artists/new.html.erb
<div class="menu">
  <div class="container">
    <%= link_to image_tag("back.png"), locations_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
<h1>New artist</h1>

<%= render 'form' %>

</div>

app/views/artists/show.html.erb
<div class="menu">
  <div class="container">
    <%= link_to image_tag("back.png"), locations_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
  <h1><%= @artist.artist %></h1>
  <img src="<%= @artist.photo_url  %>" >
  <div class="rating">
    <p> Number of Stars: <%=  @artist.rating %></p>
  </div>
  <div class="description">
    <p><%= @artist.description %>
    </p>
  </div>
  <div class="prof_buttons">
    <%= link_to 'Tip/Review', "/artists/#{@artist.id}/tip", class: "button tip" %>
    <%= link_to 'Add Location', new_location_path, class: "button add_location" %>
  </div>
  <div class="reviews">
    <h3>Reviews</h3>
    <div class="review">
      <ul>
        <li><h4>Reviewed by: Ethan Gould</h4></li>
        <li>Thought he was cool, I really like the name</li></br>
        <li><b>Location Seen:</b> Government Center Plaza</li>
      </ul>
    <div style="clear:both"></div>
  </div>
</div>

app/views/artists/tip.html.erb
<div class="menu">
  <div class="container">
    <%= link_to image_tag('back.png'), artist_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
  <div class="artist_tip">
    <%= image_tag @artist.photo_url %><h2><%= @artist.artist %></h2>
  </div>
  <div class="tips">
    <h3>Leave a Tip</h3>
    <a href="javascript:void(0)" class="button givetip active 1">$1</a>
    <a href="javascript:void(0)" class="button givetip active 2">$2</a>
    <a href="javascript:void(0)" class="button givetip active 5 last">$5</a>
    <div style="clear:both"></div>
    <input placeholder="Other dollar amount"><a href="" class="button check"><%= image_tag 'check.png' %>
    <div style="clear:both"></div>
  </div>
  <div class="givereview">
    <h3>Rate the Artist</h3>
    <h1>* * * * *</h1><br>
  </div>
  <a href="" class="button submit">Submit</a>
</div>

app/views/landing_page/index.html.erb
<div class="container home">
  <center><%= image_tag 'http://i.imgur.com/BSxOfrn.png', class: "logo_landing" %>
  <p>The easy way to find great street performers in your area</p></center>
  <div class="landing_buttons">
    <%= link_to 'Watchers', "/locations", class: "button watch", 'data-no-turbolink' => true %>
    <a href="#" class="button artist">Artist</a></br>
    <%= link_to 'Report a Location', new_location_path, class: "button location" %>
    <p><a href="">Learn More</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streetperformr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: 'Artist Name' %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: 'Description' %>
  </div>
  <div class="field">
    <%= f.text_field :address, placeholder: 'Address' %>
  </div>
  <div class="actions">
    <%= f.submit 'Report Performer Location' %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>



<div class="menu">
  <div class="container">
    <%= link_to image_tag('back.png'), root_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
  <div style='width: 100%'>
    <div id="map" style='width: 100%; height: 250px;'></div>
  </div>
    <% @artists.each do |artist| %>
    <div class="artist_prof">
      <% if artist.photo_url %>
        <%= link_to image_tag(artist.photo_url), artist %>
      <% else %>
        <%= link_to image_tag('user_profile.jpg'), artist %>
      <% end %>
        <ul>
          <li><h3><%= link_to artist.artist, artist %></h3></li>
          <li><h4><%= artist.genre %></h4></li>
          <li><h4>Rating: <%= artist.rating %></h4></li>
        </ul>
        <div style="clear: both"></div>
    </div>
    <% end %>
</div>

<div class="container">
    <%= link_to 'Report Performer Location', new_location_path, class: 'location button' %>
</div>



<div id="map">
<script type="text/javascript" charset="utf-8">
<!-- DONT TOUCH MAP IS WORKING -->
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {
    disableDefaultUI: true
  },
  internal: {
    id: 'map'
  }},
  function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
<!-- DONT TOUCH MAP IS WORKING -->
</script>
</div>

app/views/locations/new.html.erb
<div class="menu">
  <div class="container">
    <%= link_to image_tag("back.png"), locations_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
<div id="field_header">
  <h3>Enter Performer Location</h3>
</div>

<%= render 'form' %>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= 'Performer Location Added' %></p>

<!-- <p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p> -->

<p>
  <strong>Artist:</strong>
  <%= @location.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path, 'data-no-turbolink' => true %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: 'Artist Name' %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: 'Description' %>
  </div>
  <div class="field">
    <%= f.text_field :address, placeholder: 'Address' %>
  </div>
  <div class="actions">
    <%= f.submit 'Report Performer Location' %>
  </div>
<% end %>

app/views/users/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>



<div class="menu">
  <div class="container">
    <%= link_to image_tag('back.png'), root_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
  <div style='width: 100%'>
  <div id="map" style='width: 100%; height: 250px;'></div>
  </div>
    <% @artists.each do |artist| %>
    <div class="artist_prof">
      <% if artist.photo_url %>
        <%= link_to image_tag(artist.photo_url), artist %>
      <% else %>
        <%= link_to image_tag('user_profile.jpg'), artist %>
      <% end %>
        <ul>
          <li><h3><%= link_to artist.artist, artist %></h3></li>
          <li><h4><%= artist.genre %></h4></li>
          <li><h4>Rating: <%= artist.rating %></h4></li>
        </ul>
        <div style="clear: both"></div>
    </div>
    <% end %>
</div>

<div class="container">
    <%= link_to 'Report Performer Location', new_user_path, class: 'location button' %>
</div>



<div id="map">
<script type="text/javascript" charset="utf-8">
<!-- DONT TOUCH MAP IS WORKING -->
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {
    disableDefaultUI: true
  },
  internal: {
    id: 'map'
  }},
  function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
<!-- DONT TOUCH MAP IS WORKING -->
</script>
</div>

app/views/users/new.html.erb
<div class="menu">
  <div class="container">
    <%= link_to image_tag("back.png"), users_path, class: 'back' %>
    <%= image_tag 'logo_text.png', class: 'logo' %>
  </div>
</div>
<div class="container">
<div id="field_header">
  <h3>Enter Performer Location</h3>
</div>

<%= render 'form' %>
</div>